app = "schedule-bot-2"  # তোমার Fly app নাম

primary_region = "ams"

[build]
  image = "python:3.10-slim"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python3 main.py"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
