app = "your-app-name"  # এখানে ছোট হাতের অক্ষর, সংখ্যা, ড্যাশ ব্যবহার করো

[build]
  dockerfile = "./Dockerfile"

[env]
  SESSION_STRING = "your_session_string_here"
  API_ID = "your_api_id_here"
  API_HASH = "your_api_hash_here"
  ADMIN_ID = "your_admin_id_here"
  GROUPS = "-1001234567890,-1009876543210"

[deploy]
  release_command = ""
