app = "schedule-bot-2"
primary_region = "ams"

[build]
  # no need to specify image here, Fly will use Dockerfile

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python3 main.py"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
