app = "schedule-bot"

[build]
  dockerfile = "./Dockerfile"

[env]
  SESSION_STRING = "your_session_string"
  API_ID = "your_api_id"
  API_HASH = "your_api_hash"
  ADMIN_ID = "your_admin_id"
  GROUPS = "-1001234567890,-1009876543210"
